name: ox_tech
description: Cross platform application for native wearable device.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.2
  csv: ^5.0.2
  percent_indicator: ^4.0.1
  intl: ^0.17.0
  charts_flutter: ^0.12.0
  video_player: ^2.7.1
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.2
  provider: ^6.0.5
  cloud_firestore: ^4.9.3
  rounded_loading_button: ^2.1.0
  font_awesome_icon_class: ^0.0.6
  font_awesome_flutter: ^10.5.0
  shared_preferences: ^2.0.8
  connectivity_plus: ^4.0.2
  riverpod_context: ^0.3.0
  flutter_riverpod: ^2.4.3
  firebase_database: ^10.2.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
#  web:
#    generate: true
#    image_path: "path/to/image.png"
#    background_color: "#hexcode"
#    theme_color: "#hexcode"
#  windows:
#    generate: true
#    image_path: "path/to/image.png"
#    icon_size: 48 # min:48, max:256, default: 48
#  macos:
#    generate: true
#    image_path: "path/to/image.png"


flutter:
  uses-material-design: true
  assets:
  #TO add assets to application,add an assets like this change error from this site https://www.flutterbeads.com/unable-to-load-asset-in-flutter/
    - assets/images/
  fonts:
    - family: LibreBaskerville
      fonts:
        - asset: assets/fonts/LibreBaskerville-Regular.ttf
          weight: 400
        - asset: assets/fonts/LibreBaskerville-Bold.ttf
          weight: 700