// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb7MGhbDu5xgTwfyRCBmP1FvdGE4OGaaU',
    appId: '1:311182396675:web:fc3d412d798b61b0f12d36',
    messagingSenderId: '311182396675',
    projectId: 'x-ring-mvp-dev',
    authDomain: 'x-ring-mvp-dev.firebaseapp.com',
    storageBucket: 'x-ring-mvp-dev.appspot.com',
    measurementId: 'G-6RF154XXLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoZpMbzQkW1XliGYf4QOzh5vIHD2ufino',
    appId: '1:311182396675:android:088950e445184b58f12d36',
    messagingSenderId: '311182396675',
    projectId: 'x-ring-mvp-dev',
    storageBucket: 'x-ring-mvp-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1WuABEgWZeI_qSQ5NIwfigX_QLRz8h-Q',
    appId: '1:311182396675:ios:c2fa0c67d92fac80f12d36',
    messagingSenderId: '311182396675',
    projectId: 'x-ring-mvp-dev',
    storageBucket: 'x-ring-mvp-dev.appspot.com',
    androidClientId: '311182396675-32rlrckv1d6b72jm2ius8sbrdukj4snf.apps.googleusercontent.com',
    iosClientId: '311182396675-aanefcu2o0s2strkmp7mh3ai75upd37e.apps.googleusercontent.com',
    iosBundleId: 'com.ox.xRingMvpDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1WuABEgWZeI_qSQ5NIwfigX_QLRz8h-Q',
    appId: '1:311182396675:ios:700397158b8f31fdf12d36',
    messagingSenderId: '311182396675',
    projectId: 'x-ring-mvp-dev',
    storageBucket: 'x-ring-mvp-dev.appspot.com',
    androidClientId: '311182396675-32rlrckv1d6b72jm2ius8sbrdukj4snf.apps.googleusercontent.com',
    iosClientId: '311182396675-aanefcu2o0s2strkmp7mh3ai75upd37e.apps.googleusercontent.com',
    iosBundleId: 'com.ox.xRingMvpDev.RunnerTests',
  );
}
